export const FakeArticle = `
May was focused on a ton of improvements (mainly for the ​[Entity Builder​](https://saasrock.com/entity-builder?ref=saasrock.com&utm_content=v0-8-8)):

- ⭐ **Autogenerated API Docs** with Swagger _(OpenAPI)_ and Postman
- ⭐ **Code Generator** support for new types (Multi-select, Range-number...)
- ⭐ New **Entity View Manager** at _/admin/entities/views_
- ⭐ New **Subscriptions** page at _/admin/accounts/subscriptions_
- ⭐ **Row Hooks**: Added functions to customize your BL _(onBeforeGetAll, onBeforeEdit, onAfterEdit...)_

And other minor fixes:

- 🔨 **Yes-Code**: Multi-select missing in generated files #304
- 🔨 **Multi-select** attribute not added to Yes-Code Helper #302
- 🔨 Row Form **Number Input** cannot clear #303
- 🔨 Footer Block needs translations #272
- 🔨 Edit entity gives the wrong path... #268
- 🔨 ActionResultModal no way to set title #264

Links:

- ​[Tweet](https://twitter.com/AlexandroMtzG/status/1664764186772008960)​
- Video - ​[Autogenerated Docs API](https://www.loom.com/share/b693c877282348408f7ab0d36dc974b8)
- ​Video - ​[Account/Tenant Types and Relationships](https://www.loom.com/share/a4b5f9176abc4eac85de8e0bc84bb16b)
- ​​[Demo](https://saasrock.com/entity-builder?ref=saasrock.com&utm_content=v0-8-8)​ - Entity Builder _(Form/List previews, API docs, Code generator)_​
- [Demo](https://saasrock.com/api/docs?ref=saasrock.com&utm_content=v0-8-8)​ - Swagger Docs​
- [Demo](https://saasrock.com/postman_collection.json?ref=saasrock.com&utm_content=v0-8-8)​ - Postman Collection
- ​[Changelog](https://saasrock.com/changelog?ref=saasrock.com&utm_content=v0-8-8)​ - SaasRock v0.8.8

---

### What's Next?

I've said this many times, but hopefully this month I can pull any of these:

- **Knowledge Base** _(intercom-like help center, ​preview​)_
- **Help Desk** - Enterprise 🚀 _(accounts submit tickets)
- **Affiliates & Referrals** - Enterprise 🚀 _(create affiliate links to track signups/commissions)_

Let me know what you think of these improvements on the ​[Discord server​](https://discord.gg/KMkjU2BFn9)!
`;
